config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  devise_for :admin_users
  root to: "courses#index"

  namespace :admin do
    root to: "course_assigns#index"
    resources :admin_users, :users, :courses, :course_assigns, :sections
    resources :items, only: [:index, :destroy]
    resources :slides, :questions, except: [:index, :destroy]
  end

  resources :courses, only: [:index, :show] do
    resources :learning do
      post '' => 'learning#answer'
    end
  end
end

app/models/slide.rb
class Slide < ActiveRecord::Base
  validates :name, presence: true
  
  has_one :item, as: :itemable, dependent: :destroy
  accepts_nested_attributes_for :item, update_only: true
end

app/controllers/admin/slides_controller.rb
class Admin::SlidesController < Admin::AdminController

  def new
    @resource = Slide.new
    @resource.build_item
  end

  def create
    @resource = Slide.new(permitted_params)
    if @resource.save
      respond_to do |format|
        format.html { redirect_to polymorphic_path([:admin, Item]), notice: "Слайд создан" } 
        format.json { render json: @resource }
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @resource = Slide.find(params[:id])
    if @resource.update_attributes(permitted_params)
      respond_to do |format|
        format.html { redirect_to polymorphic_path([:admin, Item]), notice: "Слайд обновлен" } 
        format.json { render json: @resource }
      end
    else
      respond_to do |format|
        format.html { render :edit }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def permitted_params
    params.require(:slide).permit(:name, :content, :item_attributes => [:name, :position, :section_id])
  end
  def set_resource
    @resource = Slide.find(params[:id])
  end
end

app/views/admin/slides/_crud.haml
= link_to icon('eye'), polymorphic_path([:admin, record.itemable]), class: "btn btn-xs btn-info btn-flat", title: "Просмотр"
= link_to icon('pencil'), edit_polymorphic_path([:admin,  record.itemable]), class: "btn btn-xs btn-warning btn-flat", title: "Редактировать"
= link_to icon('trash'), polymorphic_path([:admin,  record]), class: "btn btn-xs btn-danger btn-flat", title: "Удалить", data: {confirm: "Вы уверены?", method: :delete}

app/views/admin/slides/_form.haml
= bootstrap_form_for [:admin, @resource], layout: :horizontal, label_col: "col-sm-3", control_col: "col-sm-9", label_errors: true, validate: true do |f|
  = f.alert_message "Сохранение не удалось из-за следующих ошибок:"
  .well
    = f.fields_for :item do |ff|
      = ff.text_field :name
      = ff.number_field :position
      = ff.form_group label: { text: "Раздел" } do
        Текущий раздел:
        = @resource.item.section.present? ? @resource.item.section.name : "Корневой раздел"
        = ff.hidden_field :section_id, id: "slide_item_sttributes_section_id_hidden"

        %table#selectSlideItemSectionTree.table.table-hover.table-striped
          %colgroup
            %col{width: "100px"}
            %col{width: "*"}
          %thead
            %tr
              %th ID
              %th Раздел
          %tbody
  .well
    = f.text_field :name
    = f.form_group label: { text: "Содержание" } do
      .slide-sample
        .panel.headings
          %h3#item_section_name= @resource.item.section.present? ? @resource.item.section.name : "Выберите раздел"
          %h4#item_name= @resource.name.present? ? @resource.name : "Введите имя слайда"
        .panel
          - if action_name == "new"
            .content= f.text_area_without_bootstrap :content, value: "<h1>Нажмите для редактирования</h1>"
          - else
            .content= f.text_area_without_bootstrap :content
          .footer
            .row
              .col-lg-2
                = icon('chevron-left', nil, class: "fa-2x")
              .col-lg-8
                %center
                  %span.label.label-success 1
                  %span.label.label-success 2
                  %span.label.label-success 3
                  %span.label.label-primary 4
                  %span.label.label-success 5
                  %span.label.label-success 6
                  %span.label.label-danger ?
                  %span.label.label-success 8
                  %span.label.label-success 9
                  %span.label.label-danger ?
              .col-lg-2.text-right
                = icon('chevron-right', nil, class: "fa-2x")

      %br
      %p.text-sm.text-muted
        * Подсказка:
        %br
        %span.label.label-success 1
        \- Слайд с информацией
        %br
        %span.label.label-danger ?
        \- Слайд с вопросом
        %br
        %span.label.label-primary 4
        \- Текущий слайд

  = f.submit class: "btn btn-primary btn-flat"

app/views/admin/slides/show.haml
%section.content-header
  %h1
    Слайд
    = "##{@resource.item.id}"
    %small Просмотр
  %ol.breadcrumb
    %li
      = link_to admin_root_path do
        %i.fa.fa-dashboard
        Панель управления
    %li
      = link_to polymorphic_path([:admin, Item]) do
        = @resource.model_name.human(count: 1.1)
    %li.active= "##{@resource.item.id}"
%section.content
  = render "partials/alerts"
  .box.box-primary
    .box-body
      %table.table.table-bordered.table-striped{style: "width: 100%"}
        %tr
          %td{style: "width: 25%"} ID
          %td
            = @resource.item.id
        %tr
          %td{style: "width: 25%"} Техническое имя
          %td
            = @resource.item.name
        %tr
          %td{style: "width: 25%"} Курсы и раздел
          %td
            = @resource.item.section.courses.present? ? @resource.item.section.courses.map{|c| "#{c.try(:name)} <i class='fa fa-angle-right'></i> #{@resource.item.section.name}"}.join("<br />").html_safe : @resource.item.section.name
        %tr
          %td{style: "width: 25%"} Позиция
          %td
            = @resource.item.position
        %tr
          %td{style: "width: 25%"} Название слайда
          %td
            = @resource.name
        %tr
          %td{style: "width: 25%"} Содержание
          %td
            .slide-sample
              .panel.headings
                %h3= @resource.item.section.name
                %h4= @resource.name
              .panel
                .content.cke_textarea_inline= @resource.content.html_safe
                .footer
                  .row
                    .col-lg-2
                      = icon('chevron-left', nil, class: "fa-2x")
                    .col-lg-8
                      %center
                        %span.label.label-success 1
                        %span.label.label-success 2
                        %span.label.label-success 3
                        %span.label.label-primary 4
                        %span.label.label-success 5
                        %span.label.label-success 6
                        %span.label.label-danger ?
                        %span.label.label-success 8
                        %span.label.label-success 9
                        %span.label.label-danger ?
                    .col-lg-2.text-right
                      = icon('chevron-right', nil, class: "fa-2x")
        %tr
          %td{style: "width: 25%"} Создан
          %td
            = @resource.created_at
        %tr
          %td{style: "width: 25%"} Обновлен
          %td
            = @resource.updated_at
      %br
      %p
        = link_to "Редактировать", edit_admin_slide_path(@resource.id), class: "btn btn-warning"
        = link_to "Удалить", admin_item_path(@resource.item.id), data: { method: :delete, confirm: "Вы уверены?" }, class: "btn btn-danger"