config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  devise_for :admin_users
  root to: "courses#index"

  namespace :admin do
    root to: "course_assigns#index"
    resources :admin_users, :users, :courses, :course_assigns, :sections
    resources :items, only: [:index, :destroy]
    resources :slides, :questions, except: [:index, :destroy]
  end

  resources :courses, only: [:index, :show] do
    resources :learning do
      post '' => 'learning#answer'
    end
  end
end

app/models/section.rb
class Section < ActiveRecord::Base
  validates :name, :course_ids, presence: true

  has_and_belongs_to_many :courses
  has_many :items

  has_ancestry
end

app/controllers/admin/sections_controller.rb
class Admin::SectionsController < Admin::AdminController

  def index
    if params[:select2].present?
      @resource = controller_name.classify.constantize.where("name ILIKE ?", '%' + params[:select2] + '%').offset(params[:page]).order(name: :asc)
    end
    if params[:tree].present?
      if params[:key]
        @resource = Section.find(params[:key]).children
      else
        @resource = Section.roots
      end
    end
    respond_to do |format|
      format.html
      format.json do
        if params[:select2].present?
          render json: @resource.map{|r| {id: r.id, text: r.name} }
        elsif params[:tree].present?
          render json: @resource.map{|r| {id: r.id, title: r.name, description: r.description, lazy: r.has_children?} }
        else
          render json: (controller_name.classify+"Datatable").constantize.new(view_context) 
        end
      end
    end
  end

  private
  def permitted_params
    params.require(:section).permit(:name, :description, :parent_id, :course_ids => [])
  end
  def set_resource
    @resource = Section.includes(:courses).find(params[:id])
  end
end

app/views/admin/sections/_form.haml
= bootstrap_form_for [:admin, @resource], layout: :horizontal, label_col: "col-sm-3", control_col: "col-sm-9", label_errors: true, validate: true do |f|
  = f.alert_message "Сохранение не удалось из-за следующих ошибок:"
  .well
    = f.text_field :name
    = f.text_area :description
    = f.form_group label: { text: "Родительский раздел" } do
      Текущий раздел:
      = @resource.parent_id ? @resource.name : "Корневой раздел"
      = f.hidden_field :parent_id, id: "section_parent_id_hidden"
      = f.radio_button :parent_id, "", checked: action_name == 'new' || @resource.parent_id == nil
      = f.label :parent_id, "Корневой раздел"
      %table#selectSectionTree.table.table-hover.table-striped
        %colgroup
          %col{width: "100px"}
          %col{width: "*"}
        %thead
          %tr
            %th ID
            %th Раздел
        %tbody
    = f.collection_check_boxes :course_ids, Course.all, :id, :name
  = f.submit class: "btn btn-primary btn-flat"

app/views/admin/sections/index.haml
%section.content-header
  %h1
    = icon('folder-open')
    Разделы
    %small Отдельные главы курса обучения
  %ol.breadcrumb
    %li
      = link_to admin_root_path do
        %i.fa.fa-dashboard
        Панель управления
    %li.active Разделы
%section.content
  = render partial: "partials/alerts"
  /
    .box.box-primary
      .box-body
        %p= link_to icon("plus", "Создать раздел"), new_admin_section_path, class: "btn btn-primary btn-lg btn-flat"
        %table.table.table-bordered.table-striped#sectionsTable{data: {source: admin_sections_path(format: :json)}}
          %thead
            %tr
              %th ID
              %th Название
              %th Описание
              %th Действия

  .box.box-primary
    .box-body
      %p= link_to icon("plus", "Создать раздел"), new_admin_section_path, class: "btn btn-primary btn-lg btn-flat"
      %table#sectionsTree.table.table-hover.table-striped
        %colgroup
          %col{width: "30px"}
          %col{width: "*"}
          %col{width: "400px"}
          %col{width: "100px"}
        %thead
          %tr
            %th ID
            %th Название
            %th Описание
            %th Действия
        %tbody

app/views/admin/sections/show.haml
%section.content-header
  %h1
    = @resource.model_name.human(count: 1).mb_chars.capitalize
    = "##{@resource.id}"
    %small Просмотр
  %ol.breadcrumb
    %li
      = link_to admin_root_path do
        %i.fa.fa-dashboard
        Панель управления
    %li
      = link_to polymorphic_path([:admin, @resource]) do
        = @resource.model_name.human(count: 1.1)
    %li.active= "##{@resource.id}"
%section.content
  = render "partials/alerts"
  .box.box-primary
    .box-body
      %table.table.table-bordered.table-striped{style: "width: 100%"}
        %tr
          %td{style: "width: 25%"} ID
          %td
            = @resource.id
        %tr
          %td{style: "width: 25%"} Название раздела
          %td
            = @resource.name
        %tr
          %td{style: "width: 25%"} Описание раздела
          %td
            = @resource.description
        %tr
          %td{style: "width: 25%"} Курсы обучения
          %td
            - @resource.courses.each do |course|
              %p= course.name
        %tr
          %td{style: "width: 25%"} Создан
          %td
            = @resource.created_at
        %tr
          %td{style: "width: 25%"} Обновлен
          %td
            = @resource.updated_at
      %br
      %p
        = link_to "Редактировать", edit_admin_section_path(@resource.id), class: "btn btn-warning"
        = link_to "Удалить", admin_section_path(@resource.id), data: { method: :delete, confirm: "Вы уверены?" }, class: "btn btn-danger"