config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  devise_for :admin_users
  root to: "courses#index"

  namespace :admin do
    root to: "course_assigns#index"
    resources :admin_users, :users, :courses, :course_assigns, :sections
    resources :items, only: [:index, :destroy]
    resources :slides, :questions, except: [:index, :destroy]
  end

  resources :courses, only: [:index, :show] do
    resources :learning do
      post '' => 'learning#answer'
    end
  end
end

app/controllers/admin/courses_controller.rb
class Admin::CoursesController < Admin::AdminController

  private
  def permitted_params
    params.require(:course).permit(:name, :description)
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!
  layout 'learning'

  def index
    @user_courses = CourseAssign
                    .eager_load(:course)
                    .where(user_id: current_user.id)
                    .order(created_at: :desc)
  end

  def show
    @user_course = CourseAssign
                    .find(params[:id])
    @sections = @user_course.course.sections
    respond_to do |format|
      format.html
      format.js { render layout: false}
    end
  end
end

app/views/courses/_sections.haml
%h3= @user_course.course.name
%h5= @user_course.course.description
%h4 Содержание курса:
%ul
  - @sections.present? && @sections.each do |section|
    %li= section.name
    - if section.has_children?
      %ul
        - section.children.each do |ss|
          %li= ss.name
          - if ss.has_children?
            %ul
              - ss.children.each do |sss|
                %li= sss.name
.pull-right
  = link_to "Начать курс", course_learning_path(@user_course.id, @user_course.course.sections.first.items.order(position: :asc)[0].id), class: "btn btn-lg btn-primary"
.clearfix

app/views/courses/index.haml
.padding-2
  .row
    .col-lg-4
      .panel.padding-1
        #left_side
          %h3 Мои программы обучения
          - @user_courses.each do |course|
            = link_to course_path(course), remote: true, class: "btn btn-block btn-default" do
              %h4.text-left= course.course.name
              %p.text-left= course.course.description
    .col-lg-8
      .panel.padding-2
        #course_description
          %h1
            Добро пожаловать в онлайн-центр
            %br
            подготовки и аттестации
            %br
            Приморского морского
            %br
            учебно-тренажерного центра.
            %br
            %br
          %h2
            = icon('chevron-left') 
            Выберите программу обучения

app/views/courses/show.js.erb
$('#course_description')
  .empty()
  .html(
    "<%= j render 'sections' %>"
  );