config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  devise_for :admin_users
  root to: "courses#index"

  namespace :admin do
    root to: "course_assigns#index"
    resources :admin_users, :users, :courses, :course_assigns, :sections
    resources :items, only: [:index, :destroy]
    resources :slides, :questions, except: [:index, :destroy]
  end

  resources :courses, only: [:index, :show] do
    resources :learning do
      post '' => 'learning#answer'
    end
  end
end

app/views/admin/admin/edit.haml
%section.content-header
  %h1
    = @resource.model_name.human(count: 1.1)
    %small= t("activerecord.models.#{@resource.model_name.to_s.underscore}.description")
  %ol.breadcrumb
    %li
      = link_to admin_root_path do
        %i.fa.fa-dashboard
        Панель управления
    %li
      = link_to polymorphic_path([:admin, @resource]) do
        = @resource.model_name.human(count: 1.1)
    %li.active Редактирование
%section.content
  = render partial: "partials/alerts"
  .box.box-primary
    .box-body
      = render 'form'

app/views/admin/admin/index.haml
%section.content-header
  %h1
    Работает
    %small Optional description
  %ol.breadcrumb
    %li
      %a{:href => "#"}
        %i.fa.fa-dashboard
        Level
    %li.active Here
%section.content
  = render partial: "partials/alerts"

app/views/admin/admin/new.haml
%section.content-header
  %h1
    = @resource.model_name.human(count: 1.1)
    %small= t("activerecord.models.#{@resource.model_name.to_s.underscore}.description")
  %ol.breadcrumb
    %li
      = link_to admin_root_path do
        %i.fa.fa-dashboard
        Панель управления
    %li
      = link_to polymorphic_path([:admin, @resource]) do
        = @resource.model_name.human(count: 1.1)
    %li.active Создание
%section.content
  = render partial: "partials/alerts"
  .box.box-primary
    .box-body
      = render 'form'

app/views/admin/admin/show.haml
%section.content-header
  %h1
    = @resource.model_name.human(count: 1).mb_chars.capitalize
    = "##{@resource.id}"
    %small Просмотр
  %ol.breadcrumb
    %li
      = link_to admin_root_path do
        %i.fa.fa-dashboard
        Панель управления
    %li
      = link_to polymorphic_path([:admin, @resource]) do
        = @resource.model_name.human(count: 1.1)
    %li.active= "##{@resource.id}"
%section.content
  = render "partials/alerts"
  .box.box-primary
    .box-body
      %table.table.table-bordered.table-striped{style: "width: 100%"}
        - @resource.attributes.each_with_index do |attribute, index|
          %tr
            %td{style: "width: 25%"}
              = t("activerecord.attributes.#{@resource.model_name.to_s.underscore}.#{attribute[0]}")
            %td
              = attribute[1]
      %br
      %p
        = link_to "Редактировать", edit_admin_user_path(@resource.id), class: "btn btn-warning"
        = link_to "Удалить", admin_user_path(@resource.id), data: { method: :delete, confirm: "Вы уверены?" }, class: "btn btn-danger"